sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F005 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F012 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F030 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F043 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F048 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F052 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F054 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F055 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F056 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F057 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F058 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F059 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F060 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F061 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F062 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F066 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F068 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F072 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F073 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F074 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F077 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F084 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F090 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F096 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F099 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F101 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F103 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F104 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F105 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F108 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F109 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F110 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F117 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F121 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F124 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F137 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F138 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F147 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F148 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F150 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F151 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F154 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F157 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F159 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F160 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F161 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F162 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly F169 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L005 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L007 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L012 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L016 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L017 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L019 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L023 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L024 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L025 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L032 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L035 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L037 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L041 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L045 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L046 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L047 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L050 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L051 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L056 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L057 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L058 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L059 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly L060 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P001 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P006 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P024 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P027 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P033 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P038 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P040 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P042 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P045 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P048 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P060 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P063 8
sh /mnt/01/eddyyeh/bin/PAV/pav.phaseI.sh ../../assembly P064 8
